"""Create PRA Registry schema

Revision ID: 0001_registry
Revises:
Create Date: 2026-09-02 11:17:19.490731
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '0001_registry'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_approvals',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('approver', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_registry_approvals_resource_id'), 'registry_approvals', ['resource_id'], unique=False)
    op.create_index(op.f('ix_registry_approvals_resource_type'), 'registry_approvals', ['resource_type'], unique=False)
    op.create_table('registry_audit_events',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('before_summary', sa.JSON(), nullable=True),
    sa.Column('after_summary', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('sequence')
    )
    op.create_index(op.f('ix_registry_audit_events_action'), 'registry_audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_registry_audit_events_resource_id'), 'registry_audit_events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_registry_audit_events_resource_type'), 'registry_audit_events', ['resource_type'], unique=False)
    op.create_index(op.f('ix_registry_audit_events_trace_id'), 'registry_audit_events', ['trace_id'], unique=False)
    op.create_table('registry_deployments',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=128), nullable=False),
    sa.Column('cluster', sa.String(length=255), nullable=False),
    sa.Column('engine_instance_selector', sa.JSON(), nullable=False),
    sa.Column('desired_model_id', sa.String(length=255), nullable=False),
    sa.Column('desired_bundle_id', sa.String(length=255), nullable=True),
    sa.Column('desired_profile_id', sa.String(length=255), nullable=True),
    sa.Column('desired_mode', sa.String(length=64), nullable=False),
    sa.Column('storage_policy', sa.JSON(), nullable=False),
    sa.Column('observability_policy', sa.JSON(), nullable=False),
    sa.Column('desired_revision', sa.Integer(), nullable=False),
    sa.Column('approval_state', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_deployments_approval_state'), 'registry_deployments', ['approval_state'], unique=False)
    op.create_index(op.f('ix_registry_deployments_cluster'), 'registry_deployments', ['cluster'], unique=False)
    op.create_index(op.f('ix_registry_deployments_environment'), 'registry_deployments', ['environment'], unique=False)
    op.create_table('registry_engine_compatibility',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('engine', sa.String(length=128), nullable=False),
    sa.Column('engine_version_range', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('bundle_id', sa.String(length=255), nullable=True),
    sa.Column('execution_mode', sa.String(length=64), nullable=False),
    sa.Column('mechanism_status', sa.String(length=64), nullable=False),
    sa.Column('quality_status', sa.String(length=64), nullable=False),
    sa.Column('economics_status', sa.String(length=64), nullable=False),
    sa.Column('recommendation_status', sa.String(length=64), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('evidence_references', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_engine_compatibility_bundle_id'), 'registry_engine_compatibility', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_registry_engine_compatibility_engine'), 'registry_engine_compatibility', ['engine'], unique=False)
    op.create_index(op.f('ix_registry_engine_compatibility_execution_mode'), 'registry_engine_compatibility', ['execution_mode'], unique=False)
    op.create_index(op.f('ix_registry_engine_compatibility_model_id'), 'registry_engine_compatibility', ['model_id'], unique=False)
    op.create_index(op.f('ix_registry_engine_compatibility_recommendation_status'), 'registry_engine_compatibility', ['recommendation_status'], unique=False)
    op.create_table('registry_models',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('repo', sa.String(length=512), nullable=False),
    sa.Column('revision', sa.String(length=255), nullable=False),
    sa.Column('architecture', sa.String(length=255), nullable=True),
    sa.Column('tokenizer', sa.String(length=512), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('license_metadata', sa.JSON(), nullable=False),
    sa.Column('parameter_class', sa.String(length=128), nullable=True),
    sa.Column('approval_state', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_models_approval_state'), 'registry_models', ['approval_state'], unique=False)
    op.create_index(op.f('ix_registry_models_deleted'), 'registry_models', ['deleted'], unique=False)
    op.create_index(op.f('ix_registry_models_provider'), 'registry_models', ['provider'], unique=False)
    op.create_index(op.f('ix_registry_models_repo'), 'registry_models', ['repo'], unique=False)
    op.create_table('registry_policies',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=255), nullable=False),
    sa.Column('selection_policy', sa.JSON(), nullable=False),
    sa.Column('storage_policy', sa.JSON(), nullable=False),
    sa.Column('session_policy', sa.JSON(), nullable=False),
    sa.Column('observability_policy', sa.JSON(), nullable=False),
    sa.Column('allowed_bundle_ids', sa.JSON(), nullable=False),
    sa.Column('allowed_model_ids', sa.JSON(), nullable=False),
    sa.Column('allowed_profile_ids', sa.JSON(), nullable=False),
    sa.Column('approval_state', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_policies_approval_state'), 'registry_policies', ['approval_state'], unique=False)
    op.create_index(op.f('ix_registry_policies_scope'), 'registry_policies', ['scope'], unique=False)
    op.create_table('registry_profiles',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('immutable_revision', sa.String(length=255), nullable=False),
    sa.Column('model_ids', sa.JSON(), nullable=False),
    sa.Column('bundle_ids', sa.JSON(), nullable=False),
    sa.Column('policy_payload', sa.JSON(), nullable=False),
    sa.Column('qualification_status', sa.String(length=64), nullable=False),
    sa.Column('approval_state', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_profiles_approval_state'), 'registry_profiles', ['approval_state'], unique=False)
    op.create_table('registry_qualifications',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('model_revision', sa.String(length=255), nullable=False),
    sa.Column('bundle_id', sa.String(length=255), nullable=True),
    sa.Column('bundle_revision', sa.String(length=255), nullable=True),
    sa.Column('engine', sa.String(length=128), nullable=False),
    sa.Column('engine_version', sa.String(length=128), nullable=True),
    sa.Column('hardware', sa.JSON(), nullable=False),
    sa.Column('workload', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('cohort_size', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('quality_gate', sa.String(length=64), nullable=False),
    sa.Column('recommendation', sa.String(length=64), nullable=False),
    sa.Column('evidence_level', sa.String(length=64), nullable=False),
    sa.Column('pra_commit', sa.String(length=64), nullable=True),
    sa.Column('artifact_links', sa.JSON(), nullable=False),
    sa.Column('annotations', sa.JSON(), nullable=False),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_qualifications_bundle_id'), 'registry_qualifications', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_registry_qualifications_engine'), 'registry_qualifications', ['engine'], unique=False)
    op.create_index(op.f('ix_registry_qualifications_mode'), 'registry_qualifications', ['mode'], unique=False)
    op.create_index(op.f('ix_registry_qualifications_model_id'), 'registry_qualifications', ['model_id'], unique=False)
    op.create_index(op.f('ix_registry_qualifications_profile_id'), 'registry_qualifications', ['profile_id'], unique=False)
    op.create_index(op.f('ix_registry_qualifications_workload'), 'registry_qualifications', ['workload'], unique=False)
    op.create_table('registry_bundles',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('immutable_revision', sa.String(length=255), nullable=False),
    sa.Column('base_model_id', sa.String(length=255), nullable=False),
    sa.Column('base_model_revision', sa.String(length=255), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('structural_adapter_status', sa.String(length=64), nullable=False),
    sa.Column('learned_adapters', sa.JSON(), nullable=False),
    sa.Column('profile_ids', sa.JSON(), nullable=False),
    sa.Column('engine_compatibility', sa.JSON(), nullable=False),
    sa.Column('qualification_summary', sa.JSON(), nullable=False),
    sa.Column('trust', sa.String(length=128), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('checksums', sa.JSON(), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=64), nullable=False),
    sa.Column('approval_state', sa.String(length=32), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_model_id'], ['registry_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_bundles_approval_state'), 'registry_bundles', ['approval_state'], unique=False)
    op.create_index(op.f('ix_registry_bundles_base_model_id'), 'registry_bundles', ['base_model_id'], unique=False)
    op.create_index(op.f('ix_registry_bundles_immutable_revision'), 'registry_bundles', ['immutable_revision'], unique=False)
    op.create_index(op.f('ix_registry_bundles_lifecycle_state'), 'registry_bundles', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_registry_bundles_trust'), 'registry_bundles', ['trust'], unique=False)
    op.create_table('registry_artifact_sources',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('bundle_id', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('locator', sa.String(length=1024), nullable=False),
    sa.Column('credential_reference', sa.String(length=255), nullable=True),
    sa.Column('immutable_revision', sa.String(length=255), nullable=False),
    sa.Column('digest', sa.String(length=255), nullable=True),
    sa.Column('mirrors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['registry_bundles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_artifact_sources_bundle_id'), 'registry_artifact_sources', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_registry_artifact_sources_source_type'), 'registry_artifact_sources', ['source_type'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registry_artifact_sources_source_type'), table_name='registry_artifact_sources')
    op.drop_index(op.f('ix_registry_artifact_sources_bundle_id'), table_name='registry_artifact_sources')
    op.drop_table('registry_artifact_sources')
    op.drop_index(op.f('ix_registry_bundles_trust'), table_name='registry_bundles')
    op.drop_index(op.f('ix_registry_bundles_lifecycle_state'), table_name='registry_bundles')
    op.drop_index(op.f('ix_registry_bundles_immutable_revision'), table_name='registry_bundles')
    op.drop_index(op.f('ix_registry_bundles_base_model_id'), table_name='registry_bundles')
    op.drop_index(op.f('ix_registry_bundles_approval_state'), table_name='registry_bundles')
    op.drop_table('registry_bundles')
    op.drop_index(op.f('ix_registry_qualifications_workload'), table_name='registry_qualifications')
    op.drop_index(op.f('ix_registry_qualifications_profile_id'), table_name='registry_qualifications')
    op.drop_index(op.f('ix_registry_qualifications_model_id'), table_name='registry_qualifications')
    op.drop_index(op.f('ix_registry_qualifications_mode'), table_name='registry_qualifications')
    op.drop_index(op.f('ix_registry_qualifications_engine'), table_name='registry_qualifications')
    op.drop_index(op.f('ix_registry_qualifications_bundle_id'), table_name='registry_qualifications')
    op.drop_table('registry_qualifications')
    op.drop_index(op.f('ix_registry_profiles_approval_state'), table_name='registry_profiles')
    op.drop_table('registry_profiles')
    op.drop_index(op.f('ix_registry_policies_scope'), table_name='registry_policies')
    op.drop_index(op.f('ix_registry_policies_approval_state'), table_name='registry_policies')
    op.drop_table('registry_policies')
    op.drop_index(op.f('ix_registry_models_repo'), table_name='registry_models')
    op.drop_index(op.f('ix_registry_models_provider'), table_name='registry_models')
    op.drop_index(op.f('ix_registry_models_deleted'), table_name='registry_models')
    op.drop_index(op.f('ix_registry_models_approval_state'), table_name='registry_models')
    op.drop_table('registry_models')
    op.drop_index(op.f('ix_registry_engine_compatibility_recommendation_status'), table_name='registry_engine_compatibility')
    op.drop_index(op.f('ix_registry_engine_compatibility_model_id'), table_name='registry_engine_compatibility')
    op.drop_index(op.f('ix_registry_engine_compatibility_execution_mode'), table_name='registry_engine_compatibility')
    op.drop_index(op.f('ix_registry_engine_compatibility_engine'), table_name='registry_engine_compatibility')
    op.drop_index(op.f('ix_registry_engine_compatibility_bundle_id'), table_name='registry_engine_compatibility')
    op.drop_table('registry_engine_compatibility')
    op.drop_index(op.f('ix_registry_deployments_environment'), table_name='registry_deployments')
    op.drop_index(op.f('ix_registry_deployments_cluster'), table_name='registry_deployments')
    op.drop_index(op.f('ix_registry_deployments_approval_state'), table_name='registry_deployments')
    op.drop_table('registry_deployments')
    op.drop_index(op.f('ix_registry_audit_events_trace_id'), table_name='registry_audit_events')
    op.drop_index(op.f('ix_registry_audit_events_resource_type'), table_name='registry_audit_events')
    op.drop_index(op.f('ix_registry_audit_events_resource_id'), table_name='registry_audit_events')
    op.drop_index(op.f('ix_registry_audit_events_action'), table_name='registry_audit_events')
    op.drop_table('registry_audit_events')
    op.drop_index(op.f('ix_registry_approvals_resource_type'), table_name='registry_approvals')
    op.drop_index(op.f('ix_registry_approvals_resource_id'), table_name='registry_approvals')
    op.drop_table('registry_approvals')
    # ### end Alembic commands ###
