"""MLX transport and unified-memory logical bridges for PRA."""

from .adapter import MLXEngineAdapter, MLXNativeExecutor
from .native import (
    MLXInProcessNativeExecutor,
    MLXNativeLayerKV,
    MLXNativeMemory,
    MLXNativeColdCodec,
    MLXNativeFingerprint,
    MLXPositionedKVCache,
    MLXQuantizedLayerKV,
    MLXQuantizedMemory,
    MLXSegmentedSelectedKVCache,
    MLXSelectedKVCache,
    combine_native_memories,
    dequantize_native_memory,
    deserialize_native_memory,
    encode_native_memory,
    make_native_prompt_cache,
    load_native_memory,
    quantize_native_memory,
    save_native_memory,
    compiled_segmented_selected_attention,
    segmented_selected_attention,
    serialize_native_memory,
)
from .qwen3_segmented import install_qwen3_segmented_attention
from .native_storage import MLXNativeSegmentStore

__all__ = [
    "MLXEngineAdapter",
    "MLXInProcessNativeExecutor",
    "MLXNativeExecutor",
    "MLXNativeLayerKV",
    "MLXNativeMemory",
    "MLXNativeSegmentStore",
    "MLXNativeColdCodec",
    "MLXNativeFingerprint",
    "MLXPositionedKVCache",
    "MLXQuantizedLayerKV",
    "MLXQuantizedMemory",
    "MLXSegmentedSelectedKVCache",
    "MLXSelectedKVCache",
    "combine_native_memories",
    "dequantize_native_memory",
    "deserialize_native_memory",
    "encode_native_memory",
    "make_native_prompt_cache",
    "load_native_memory",
    "quantize_native_memory",
    "save_native_memory",
    "compiled_segmented_selected_attention",
    "segmented_selected_attention",
    "install_qwen3_segmented_attention",
    "serialize_native_memory",
]
