"""Public PRA-HF API for bounded sparse native-K/V memory."""

from .config import PRAConfig
from .evaluation import evaluate_router_features
from .memory_adapter import PRAMemoryAdapter
from .model import GenerationResult, PRAForCausalLM, ReferenceHandle
from .router import PRARouter
from .hybrid_discovery import (
    DiscoveryCandidate,
    HybridDiscoveryPolicy,
    TokenChunkRecord,
    TokenNativeIndex,
)
from .iterative import (
    GistIndex,
    HierarchicalGistIndex,
    HierarchicalLocalGistRouter,
    IterativeGistRouter,
    IterativeRoutingConfig,
    IterativeRoutingResult,
    RetrievalGraph,
)
from .query_graph import QueryGraph, QueryUnitProvenance, build_query_graph
from .query_graph_cluster import connected_components, weighted_label_propagation
from .query_graph_facets import GraphQueryFacetSet, pool_hard_graph_facets
from .qk_compression import LOW_RANK_INDEX_DTYPES, LowRankRoutingIndex
from .agent_resources import (
    AgentResource,
    DiscoveryDecision,
    DiscoveryHint,
    DiscoveryMode,
    DiscoveryPolicyHints,
    DiscoveryRequest,
    DiscoveryTrace,
    IndexFingerprint,
    PersistentResourceIndex,
    ReliabilityCalibrator,
    ResourceDiscoveryEngine,
    ResourceScore,
    SideEffectClass,
    resource_uri,
)
from .tool_records import (
    ParameterSchema,
    PythonTypeSchemaCache,
    ReturnSchema,
    ToolRecord,
    ToolSchema,
    tool_record_from_callable,
)
from .auto_tool_discovery import (
    AutoEvidenceSource,
    AutoSemanticEvidence,
    AutoToolSemanticView,
    auto_tag_score,
    auto_tag_scores,
    automatic_query_terms,
    automatic_semantic_view,
    evidence_provenance_counts,
    inferred_concept_score,
    inferred_concept_scores,
    weighted_keyword_score,
    weighted_keyword_scores,
)
from .union_discovery import (
    CandidateProvenance,
    CandidateSet,
    ChannelHit,
    ToolDiscoveryMode,
    ToolDiscoveryPolicy,
    UnionStrategy,
    discover_candidate_set,
)
from .context_records import (
    ContextRecord,
    MaterializationPolicy,
    OverflowBehavior,
    RecordAtomicity,
    RecordMaterializationResult,
    RecordPolicy,
    RecordSelectionPolicy,
    RecordType,
    SelectionAuthority,
    materialize_authoritative_slice,
    tool_catalog_slice_records,
    tool_definition_record,
)

__version__ = "0.2.0rc1"

__all__ = [
    "GenerationResult",
    "CandidateProvenance",
    "CandidateSet",
    "ChannelHit",
    "ContextRecord",
    "AgentResource",
    "AutoEvidenceSource",
    "AutoSemanticEvidence",
    "AutoToolSemanticView",
    "DiscoveryDecision",
    "DiscoveryHint",
    "DiscoveryMode",
    "DiscoveryPolicyHints",
    "DiscoveryRequest",
    "DiscoveryTrace",
    "DiscoveryCandidate",
    "GistIndex",
    "HierarchicalGistIndex",
    "HierarchicalLocalGistRouter",
    "IterativeGistRouter",
    "IterativeRoutingConfig",
    "IterativeRoutingResult",
    "LOW_RANK_INDEX_DTYPES",
    "LowRankRoutingIndex",
    "IndexFingerprint",
    "PersistentResourceIndex",
    "ReliabilityCalibrator",
    "ResourceDiscoveryEngine",
    "ResourceScore",
    "HybridDiscoveryPolicy",
    "MaterializationPolicy",
    "OverflowBehavior",
    "ParameterSchema",
    "PRAConfig",
    "PRAForCausalLM",
    "PRAMemoryAdapter",
    "PRARouter",
    "PythonTypeSchemaCache",
    "RecordAtomicity",
    "RecordMaterializationResult",
    "RecordPolicy",
    "RecordSelectionPolicy",
    "RecordType",
    "ReferenceHandle",
    "ReturnSchema",
    "RetrievalGraph",
    "GraphQueryFacetSet",
    "QueryGraph",
    "QueryUnitProvenance",
    "TokenChunkRecord",
    "TokenNativeIndex",
    "SideEffectClass",
    "SelectionAuthority",
    "ToolDiscoveryMode",
    "ToolDiscoveryPolicy",
    "ToolRecord",
    "ToolSchema",
    "UnionStrategy",
    "build_query_graph",
    "auto_tag_score",
    "auto_tag_scores",
    "automatic_query_terms",
    "automatic_semantic_view",
    "connected_components",
    "evaluate_router_features",
    "discover_candidate_set",
    "evidence_provenance_counts",
    "inferred_concept_score",
    "inferred_concept_scores",
    "materialize_authoritative_slice",
    "pool_hard_graph_facets",
    "resource_uri",
    "tool_catalog_slice_records",
    "tool_definition_record",
    "tool_record_from_callable",
    "weighted_label_propagation",
    "weighted_keyword_score",
    "weighted_keyword_scores",
]
