"""Public PRA-HF API for bounded sparse native-K/V memory."""

from .config import PRAConfig
from .evaluation import evaluate_router_features
from .memory_adapter import PRAMemoryAdapter
from .model import GenerationResult, PRAForCausalLM, ReferenceHandle, RoutingResult
from .router import PRARouter
from pra_torch.execution import (
    PRAExecutionCapabilities,
    PRAExecutionPolicy,
    PRAMaterializationScope,
    PRAResidencyPolicy,
    PRARoutingLayerPolicy,
    PRASelectedIdentity,
    PRASelectionLayerScope,
    PRASelectionPlan,
    PRASelectionStage,
    get_default_execution_policy,
    set_default_execution_policy,
)
from .hybrid_discovery import (
    DiscoveryCandidate,
    HybridDiscoveryPolicy,
    TokenChunkRecord,
    TokenNativeIndex,
)
from .iterative import (
    GistIndex,
    HierarchicalGistIndex,
    HierarchicalLocalGistRouter,
    IterativeGistRouter,
    IterativeRoutingConfig,
    IterativeRoutingResult,
    RetrievalGraph,
)
from .query_graph import QueryGraph, QueryUnitProvenance, build_query_graph
from .query_graph_cluster import connected_components, weighted_label_propagation
from .query_graph_facets import GraphQueryFacetSet, pool_hard_graph_facets
from .qk_compression import LOW_RANK_INDEX_DTYPES, LowRankRoutingIndex
from .external_memory import (
    AuthContext,
    EncodingContext,
    ExternalMemoryManager,
    FileResourceResolver,
    HotMemoryHandle,
    NativeEncoding,
    PRASession,
    ResolverRegistry,
    ResourceRecord,
    ResourceResolver,
    ResourceStat,
)
from .pra_aware_training import (
    GemmaLayerTopology,
    gemma_layer_topology,
    hf_parameter_summary,
    install_hf_adaptation_regime,
)
from .agent_execution import (
    ExecutionAuthorization,
    SafeToolExecutor,
    ToolCall,
    ToolExecutionResult,
    parse_tool_call,
)
from .agent_resources import (
    AgentResource,
    DiscoveryDecision,
    DiscoveryMode,
    DiscoveryRequest,
    DiscoveryTrace,
    PersistentResourceIndex,
    ResourceDiscoveryEngine,
    SideEffectClass,
)
from .tool_records import ToolRecord, ToolSchema, tool_record_from_callable
from .toolsets import Tool, Toolset, default_toolset
from .agent import AgentTurn, PRAAgent, PRAAgentConfig
from .session_service import (
    AgentSessionState,
    InMemorySessionService,
    LocalSessionService,
    SessionConflict,
    SessionNotFound,
    SessionService,
)
from .task_context import (
    TaskDescriptor,
    TaskEvent,
    TaskEventType,
    TaskGraph,
    TaskProvenance,
    TaskRelation,
    TaskState,
    TaskStatus,
    attach_task_provenance,
    task_state_record,
)
from .task_planning import (
    ComplexityGate,
    PlannedTask,
    parse_json_plan,
    parse_markdown_plan,
    plan_events,
    validate_plan,
)
from .task_scope import (
    DetailDepth,
    ResidencyState,
    ScopeSelection,
    TaskScopePolicy,
    TaskScopeSelector,
    TaskWorkingSet,
)
from .skill_records import (
    Skill,
    SkillFolderCache,
    SkillFolderError,
    SkillFolderFormat,
    load_skill_directory,
    load_skill_folder,
)
from .capability_runtime import (
    CapabilityActivation,
    CapabilityEncodingPolicy,
    CapabilityEncodingState,
    CapabilityPaletteActivation,
    LazyCapabilityRuntime,
    SkillRecordPolicy,
    ToolRecordPolicy,
)
from .capability_sdk import AgentConfig, CapabilitySDK
from .context_records import RecordType, RecordViewName
from .context_store import LocalBackingStore, RecordAccessDenied, RecordScope
from .typed_context import (
    AdaptiveContextRecord,
    AddressView,
    AddressViewKind,
    CompressionResult,
    CompressorRegistry,
    create_adaptive_record,
)
from .adaptive_context_runtime import (
    AdaptiveContextRuntime,
    ContextPolicy,
    CursorAction,
    CursorActionResult,
    CursorOperation,
    CursorPolicy,
    DeploymentTopology,
    MaterializationEvent,
    MaterializationResult,
    RetrievalMode,
    StoragePolicy,
    TypeContextPolicy,
)
from .progressive_context import (
    ContextAction,
    ContextDecision,
    ContextExecutionResult,
    NativePRASelection,
    PRASelection,
    ProgressiveContextRuntime,
    RecordCapabilities,
)
from .runtime import (
    CompilationMode,
    HuggingFaceBackend,
    KVInterval,
    KVLayout,
    KVMaterializer,
    MaterializationPlan,
    MaterializedKV,
    NativeKV,
    PackedNativeKVStore,
    PRARuntime,
    PRARuntimeConfig,
    RuntimeBackend,
    RuntimeKVCache,
    RuntimeProfiler,
    RuntimeToolExecution,
    SelectedKVGather,
    VLLMThinBackend,
    VLLMThinRequest,
    runtime_capabilities,
)

__version__ = "0.2.0rc1"

__all__ = [
    "GenerationResult",
    "AuthContext",
    "DiscoveryCandidate",
    "GistIndex",
    "HierarchicalGistIndex",
    "HierarchicalLocalGistRouter",
    "IterativeGistRouter",
    "IterativeRoutingConfig",
    "IterativeRoutingResult",
    "LOW_RANK_INDEX_DTYPES",
    "LowRankRoutingIndex",
    "EncodingContext",
    "ExternalMemoryManager",
    "FileResourceResolver",
    "HotMemoryHandle",
    "HybridDiscoveryPolicy",
    "PRAConfig",
    "PRAExecutionCapabilities",
    "PRAExecutionPolicy",
    "PRAMaterializationScope",
    "PRAResidencyPolicy",
    "PRARoutingLayerPolicy",
    "PRASelectedIdentity",
    "PRASelectionLayerScope",
    "PRASelectionPlan",
    "PRASelectionStage",
    "PRAForCausalLM",
    "PRASession",
    "PRAMemoryAdapter",
    "PRARouter",
    "ReferenceHandle",
    "RoutingResult",
    "ResolverRegistry",
    "ResourceRecord",
    "ResourceResolver",
    "ResourceStat",
    "NativeEncoding",
    "RetrievalGraph",
    "GraphQueryFacetSet",
    "GemmaLayerTopology",
    "QueryGraph",
    "QueryUnitProvenance",
    "TokenChunkRecord",
    "TokenNativeIndex",
    "build_query_graph",
    "connected_components",
    "evaluate_router_features",
    "gemma_layer_topology",
    "hf_parameter_summary",
    "install_hf_adaptation_regime",
    "pool_hard_graph_facets",
    "weighted_label_propagation",
    "get_default_execution_policy",
    "set_default_execution_policy",
]

__all__ += [
    "AgentResource",
    "CompilationMode",
    "DiscoveryDecision",
    "DiscoveryMode",
    "DiscoveryRequest",
    "DiscoveryTrace",
    "ExecutionAuthorization",
    "HuggingFaceBackend",
    "KVInterval",
    "KVLayout",
    "KVMaterializer",
    "MaterializationPlan",
    "MaterializedKV",
    "NativeKV",
    "PackedNativeKVStore",
    "PRARuntime",
    "PRARuntimeConfig",
    "PersistentResourceIndex",
    "ResourceDiscoveryEngine",
    "RuntimeBackend",
    "RuntimeKVCache",
    "RuntimeProfiler",
    "SelectedKVGather",
    "SafeToolExecutor",
    "SideEffectClass",
    "ToolCall",
    "ToolExecutionResult",
    "VLLMThinBackend",
    "VLLMThinRequest",
    "parse_tool_call",
    "runtime_capabilities",
]

__all__ += [
    "AdaptiveContextRecord",
    "AdaptiveContextRuntime",
    "AddressView",
    "AddressViewKind",
    "AgentConfig",
    "CapabilityActivation",
    "CapabilityEncodingPolicy",
    "CapabilityEncodingState",
    "CapabilityPaletteActivation",
    "CapabilitySDK",
    "CompressionResult",
    "CompressorRegistry",
    "ContextAction",
    "ContextDecision",
    "ContextExecutionResult",
    "ContextPolicy",
    "CursorAction",
    "CursorActionResult",
    "CursorOperation",
    "CursorPolicy",
    "DeploymentTopology",
    "LazyCapabilityRuntime",
    "LocalBackingStore",
    "MaterializationEvent",
    "MaterializationResult",
    "NativePRASelection",
    "PRASelection",
    "ProgressiveContextRuntime",
    "RecordAccessDenied",
    "RecordCapabilities",
    "RecordScope",
    "RecordType",
    "RecordViewName",
    "RetrievalMode",
    "RuntimeToolExecution",
    "Skill",
    "SkillFolderCache",
    "SkillFolderError",
    "SkillFolderFormat",
    "SkillRecordPolicy",
    "StoragePolicy",
    "ToolRecord",
    "ToolRecordPolicy",
    "ToolSchema",
    "TypeContextPolicy",
    "create_adaptive_record",
    "load_skill_directory",
    "load_skill_folder",
    "tool_record_from_callable",
    "AgentSessionState",
    "AgentTurn",
    "ComplexityGate",
    "DetailDepth",
    "InMemorySessionService",
    "LocalSessionService",
    "PRAAgent",
    "PRAAgentConfig",
    "PlannedTask",
    "ResidencyState",
    "ScopeSelection",
    "SessionConflict",
    "SessionNotFound",
    "SessionService",
    "TaskDescriptor",
    "TaskEvent",
    "TaskEventType",
    "TaskGraph",
    "TaskProvenance",
    "TaskRelation",
    "TaskScopePolicy",
    "TaskScopeSelector",
    "TaskState",
    "TaskStatus",
    "TaskWorkingSet",
    "Tool",
    "Toolset",
    "attach_task_provenance",
    "default_toolset",
    "parse_json_plan",
    "parse_markdown_plan",
    "plan_events",
    "task_state_record",
    "validate_plan",
]
