observability:
  enabled: true
  service:
    environment: development
  prometheus:
    enabled: true
    host: 0.0.0.0
    port: 9464
    path: /metrics
  otel:
    enabled: true
    endpoint: http://192.168.1.102:4317
    protocol: grpc
    traces: true
    metrics: false
    sampler: parent_based_trace_id_ratio
    sample_rate: 0.01
  engine_native:
    enable_tracing: false
    enable_metrics: false
  content:
    capture: none
  grafana_url: http://192.168.1.102:3000
  trace_url: http://192.168.1.102:3200
