"""Backend protocols decoupling control semantics from physical transports."""

from __future__ import annotations

from typing import Any, Mapping, Protocol


class ObservedStateBackend(Protocol):
    async def overview(self) -> dict[str, Any]: ...
    async def engine_section(self, name: str, section: str) -> Any: ...
    async def targets(self) -> list[Any]: ...
    async def close(self) -> None: ...


class ActionBackend(Protocol):
    async def action(self, name: str, action: str, body: Mapping[str, Any]) -> Any: ...
    async def patch_config(self, name: str, body: Mapping[str, Any]) -> Any: ...


class RegistryBackend(Protocol):
    async def list(self, resource: str, *, limit: int = 200, offset: int = 0) -> dict[str, Any]: ...
    async def request(self, method: str, path: str, body: Mapping[str, Any] | None = None) -> Any: ...
    async def deployments(self) -> list[dict[str, Any]]: ...
    async def close(self) -> None: ...
